BBBB BBBBBBBB BBBBBBBBB BBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXXX
    XXXXXX
        XXXXXXXBBBBB BBBBBXXXX XX XX XXX XXXXXXX XXXX XXXXBBBBBBBB BBBBBXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXX
            XXXX X
                XXXXXXXXXXXXX XX
            X
            XXXX XX X
                XXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXX XXXXX
            X
            XXXXXXXXXX X
                XXXXXX XXXXXX
                XXXXXXX X XXXX
            X
            XXXXXXXX X
                XXXXXX XXXXX
                XXXXXX XXXX
            X
            XXXXXXXX X
                XXXXXX XXXXX
                XXXXXX XXXX
            X
        XXXXXXXX
        BBBBBBBBBBBB BBBBB
    XXXXXXX
    XXXXXX
        BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXX
                BBBBBBBBB B BBB BBB BBB
            XXXXX
            BBBBB BBBBBBBBBBBBBBB BBBBBBB
        XXXXXX
        BBBBBBBBBBBB BBBB
    XXXXXXX
XXXXXXX
