BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX
        BBBBBBBBBBB BBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX
        BBBBBBBBBBB BBBBBBBBB
    XXXXXX
BBBBBBBB BBBBBBB
